import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./custom/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" z-[-999] bg-gradient-to-b from-blue-200 to-blue-400 bg-sky-300">
        <Header />
        {children}
      </body>
    </html>
  );
}
