import type { Metadata } from "next";

import "./globals.css";
import Header from "./custom/Header";

export const metadata: Metadata = {
  title: "Colins Chege",
  description: "Generated by collodevs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className=" bg-gradient-to-b from-blue-600  bg-sky-300">
        <Header />
        {children}
      </body>
    </html>
  );
}
